# Change these first
owner: claritybhs # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Clarity BHS - STG
    url: https://staging.engagebyclarity.com/
  - name: Clarity BHS - PRD
    url: https://engagebyclarity.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://github.com/Clarity-BHS/upptime/blob/master/Clarity-Logo.png?raw=true
  name: Clarity BHS
  introTitle: "**Clarity BHS** Platform Status"
  introMessage: Clarity's innovative computer tablet, Engage, is the first tablet specifically designed for inpatient behavioral health facilities. Engage supports active treatment, improves staff workflows, and boosts financial performance.
  navbar:
    - title: Status
      href: https://clarity-bhs.github.io/upptime/
    - title: Engage By Clarity
      href: https://engagebyclarity.com/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
