# Change these first
owner: clarity-bhs # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  #- name: Engage by Clarity - STAGING
  #  url: https://staging.engagebyclarity.com/
  - name: Engage by Clarity
    url: https://engagebyclarity.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  themeUrl: https://status.engagebyclarity.com/clarity-bhs-theme.css
  cname: status.engagebyclarity.com
  #baseUrl: /upptime
  logoUrl: https://github.com/Clarity-BHS/upptime/blob/master/engage-logo.png?raw=true
  # https://github.com/Clarity-BHS/upptime/blob/master/engage-logo-small.png?raw=true
  # https://github.com/Clarity-BHS/upptime/blob/master/clarity-logo-512.png?raw=true
  # https://cdn.prod.website-files.com/669e92eba691ad0ec575cf37/669e92eba691ad0ec575cfbe_clarity_logo_knockout.svg
  name: Monitors
  introTitle: "**Engage by Clarity** Platform Status"
  introMessage: Clarity's innovative computer tablet, Engage, is the first tablet specifically designed for inpatient behavioral health facilities. Engage supports active treatment, improves staff workflows, and boosts financial performance.
  favicon: https://engagebyclarity.com/assets/front/images/favicon.ico
  navbar:
    - title: Status
      href: https://clarity-bhs.github.io/upptime/
    - title: Login
      href: https://engagebyclarity.com/
    - title: Clarity BHS, LLC
      href: https://www.claritybhs.com/
  links:
    - rel: stylesheet
      href: https://claritybhs.github.io/global.css
  assignees:
    - mitesh-clarity
    - claritybhs
    
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
